version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        volumes:
            - .:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - db
        networks:
            - laravel-network

    db:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=laravel
            - POSTGRES_USER=laravel_user
            - POSTGRES_PASSWORD=password123
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel-network

    node:
        image: node:20-alpine
        working_dir: /app
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        ports:
            - "5173:5173"
        command: sh -c "npm install && npm run dev"
        environment:
            - HOST=0.0.0.0
        networks:
            - laravel-network

volumes:
    db_data:
    node_modules:

networks:
    laravel-network:
        driver: bridge
